# Generated by Django 5.2.7 on 2025-10-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avito',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('date_add', models.TextField(blank=True, null=True)),
                ('date_update', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('seller', models.TextField(blank=True, null=True)),
                ('kolichestvo_komnat', models.TextField(blank=True, null=True)),
                ('obshchaya_ploshchad', models.TextField(blank=True, null=True)),
                ('ploshchad_kukhni', models.TextField(blank=True, null=True)),
                ('zhilaya_ploshchad', models.TextField(blank=True, null=True)),
                ('etazh', models.TextField(blank=True, null=True)),
                ('balkon_ili_lodzhiya', models.TextField(blank=True, null=True)),
                ('tip_komnat', models.TextField(blank=True, null=True)),
                ('vysota_potolkov', models.TextField(blank=True, null=True)),
                ('sanuzel', models.TextField(blank=True, null=True)),
                ('okna', models.TextField(blank=True, null=True)),
                ('remont', models.TextField(blank=True, null=True)),
                ('mebel', models.TextField(blank=True, null=True)),
                ('sposob_prodazhi', models.TextField(blank=True, null=True)),
                ('vid_sdelki', models.TextField(blank=True, null=True)),
                ('tip_doma', models.TextField(blank=True, null=True)),
                ('god_postroyki', models.TextField(blank=True, null=True)),
                ('etazhey_v_dome', models.TextField(blank=True, null=True)),
                ('passazhirskiy_lift', models.TextField(blank=True, null=True)),
                ('gruzovoy_lift', models.TextField(blank=True, null=True)),
                ('dvor', models.TextField(blank=True, null=True)),
                ('parkovka', models.TextField(blank=True, null=True)),
                ('etazh_val', models.TextField(blank=True, null=True)),
                ('etazh_count', models.TextField(blank=True, null=True)),
                ('to_magazin', models.TextField(blank=True, null=True)),
                ('to_pyaterochka', models.TextField(blank=True, null=True)),
                ('to_magnit', models.TextField(blank=True, null=True)),
                ('to_bolnitsa', models.TextField(blank=True, null=True)),
                ('to_pochta', models.TextField(blank=True, null=True)),
                ('to_bank', models.TextField(blank=True, null=True)),
                ('to_apteka', models.TextField(blank=True, null=True)),
                ('to_ozon', models.TextField(blank=True, null=True)),
                ('to_wildberries', models.TextField(blank=True, null=True)),
                ('to_yandex', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('source_from', models.TextField(blank=True, null=True)),
                ('tekhnika', models.TextField(blank=True, null=True)),
                ('v_dome', models.TextField(blank=True, null=True)),
                ('dopolnitelno', models.TextField(blank=True, null=True)),
                ('teplyy_pol', models.TextField(blank=True, null=True)),
                ('zaplanirovan_snos', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'avito',
                'managed': False,
            },
        ),
    ]
