# Generated by Django 5.2.7 on 2025-11-01 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avito',
            options={'managed': False, 'ordering': ('-rating', 'price', '-god_postroyki'), 'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартиры'},
        ),
    ]
