# Generated by Django 5.2.7 on 2025-10-30 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avito',
            options={'managed': False, 'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартиры'},
        ),
    ]
