# Generated by Django 5.2.7 on 2025-11-10 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_avito_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avito',
            options={'managed': False, 'ordering': ('-date_add', '-date_update'), 'verbose_name': 'Квартиру', 'verbose_name_plural': 'Квартиры'},
        ),
    ]
