# Generated by Django 5.2.7 on 2025-11-10 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_avito_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avito',
            options={'managed': False, 'verbose_name': 'Квартиру', 'verbose_name_plural': 'Квартиры'},
        ),
    ]
